default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: artem
  password: zse4rfvD

development:
  <<: *default
  database: notes_app_development

test:
  <<: *default
  database: notes_app_test

production:
  <<: *default
  database: notes_app_production
  username: notes_app
  password: <%= ENV['NOTES_APP_DATABASE_PASSWORD'] %>